name: build ide base image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Available build platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker Hub login
        run: echo "${{ secrets.DOCKER_PASSWORD  }}" | docker login --password-stdin -u "${{ secrets.DOCKER_USERNAME  }}"

      - name: Docker build
        run: |
          docker buildx build \
            --tag "${{ vars.IDE_BASE_IMAGE }}" \
            --build-arg IDE_BASE_IMAGE="${{ vars.IDE_BASE_IMAGE }}" \
            --push \
            --platform linux/amd64,linux/arm64/v8 \
            --file Dockerfile \
            .
